# Prometheus Metrics Collector Configuration

# Debug mode enables more verbose logging and shorter collection intervals (1 minute instead of 24 hours)
debug: false

# List of API proxies to collect metrics for
apiProxies:
  - "memento"
  - "ice-validator-v1"



# Prometheus connection settings
prometheus:
  # Prometheus server URL
  url: "http://localhost:9080"

  # Timeout for Prometheus API requests (in seconds)
  timeout: 30s

  # Optional basic auth credentials
  # username: "prometheus"
  # password: "secret"

  # Use range query instead of instant query
  # useRangeQuery: true

  # Step interval for range queries (e.g., "1h" for hourly data)
  # rangeStep: 1h

  # Metrics to collect
  metrics:
    - name: "request_count"
      # Use %s as a placeholder for the API proxy name
      # The [1h] time window calculates the increase over the last hour
      # For longer-term trends with more smoothing, consider using [1d] instead
      # See README.md section "Understanding Time Windows in Prometheus Queries" for details
      query: 'sum(increase(istio_requests_total{app="%s"}[1h])) by (app)'
      labels:
        - "app"


# Storage configuration
storage:
  # Directory where Parquet files will be stored
  outputDir: "./data"

  # Compression algorithm (snappy, gzip, lz4, zstd)
  compression: "snappy"

  # Row group size in bytes (default: 128MB)
  rowGroupSize: 134217728

  # Timeout for finalizing Parquet files (default: 180s)
  writeStopTimeout: 180s
